// CodeLens AI - Production-Ready Project Scaffold Generator
// Generates Spring Boot 3, React 19, FastAPI, Node.js, and C++ projects as real downloadable ZIP archives

import JSZip from 'jszip';

export const projectGenerator = {
  // Generate file map based on stack & options
  generateFiles(config) {
    const {
      name = 'my-project',
      stack = 'spring-boot',
      database = 'postgres',
      includeDocker = true,
      includeCi = true,
      includeSwagger = true
    } = config;

    const files = {};

    if (stack === 'spring-boot') {
      const artifactId = name.toLowerCase().replace(/[^a-z0-9-]/g, '-');
      files['pom.xml'] = `<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.3</version>
        <relativePath/>
    </parent>
    <groupId>com.codelens</groupId>
    <artifactId>${artifactId}</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <name>${name}</name>
    <description>Generated by CodeLens AI Scaffold Engine</description>

    <properties>
        <java.version>17</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        ${database === 'mysql' ? `<dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>` : `<dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>`}
        ${includeSwagger ? `<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.3.0</version>
        </dependency>` : ''}
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>`;

      files['src/main/java/com/codelens/Application.java'] = `package com.codelens;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }
}`;

      files['src/main/java/com/codelens/controller/HealthController.java'] = `package com.codelens.controller;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import java.util.Map;

@RestController
@RequestMapping("/api/v1/health")
public class HealthController {

    @GetMapping
    public ResponseEntity<Map<String, Object>> getHealth() {
        return ResponseEntity.ok(Map.of(
            "status", "UP",
            "service", "${name}",
            "timestamp", System.currentTimeMillis()
        ));
    }
}`;

      files['src/main/java/com/codelens/entity/UserAccount.java'] = `package com.codelens.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

@Entity
@Table(name = "user_accounts")
public class UserAccount {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank
    @Column(nullable = false)
    private String name;

    @Email
    @NotBlank
    @Column(nullable = false, unique = true)
    private String email;

    public UserAccount() {}

    public UserAccount(String name, String email) {
        this.name = name;
        this.email = email;
    }

    public Long getId() { return id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
}`;

      files['src/main/resources/application.properties'] = `spring.application.name=${name}
server.port=8080

# Database Configuration
${database === 'mysql' ? `spring.datasource.url=jdbc:mysql://localhost:3306/${artifactId}?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=password` : `spring.datasource.url=jdbc:postgresql://localhost:5432/${artifactId}
spring.datasource.username=postgres
spring.datasource.password=postgres`}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
`;
    } else if (stack === 'fastapi') {
      files['main.py'] = `from fastapi import FastAPI, HTTPException, status
from pydantic import BaseModel, EmailStr
from typing import List

app = FastAPI(
    title="${name} API",
    description="Engineered with CodeLens AI Scaffold Generator",
    version="1.0.0"
)

class UserSchema(BaseModel):
    id: int
    name: str
    email: EmailStr

db_users: List[UserSchema] = [
    UserSchema(id=1, name="Ada Lovelace", email="ada@example.com")
]

@app.get("/")
def read_root():
    return {"message": "Welcome to ${name}!", "status": "running"}

@app.get("/api/v1/users", response_model=List[UserSchema])
def list_users():
    return db_users

@app.post("/api/v1/users", response_model=UserSchema, status_code=status.HTTP_201_CREATED)
def create_user(user: UserSchema):
    db_users.append(user)
    return user
`;

      files['requirements.txt'] = `fastapi==0.110.0
uvicorn[standard]==0.28.0
pydantic[email]==2.6.4
pytest==8.1.1
`;
    } else if (stack === 'react') {
      files['package.json'] = `{
  "name": "${name.toLowerCase().replace(/[^a-z0-9-]/g, '-')}",
  "private": true,
  "version": "1.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "react": "^19.0.0",
    "react-dom": "^19.0.0",
    "lucide-react": "^0.359.0"
  },
  "devDependencies": {
    "@vitejs/plugin-react": "^4.2.1",
    "vite": "^5.1.6"
  }
}`;

      files['src/App.jsx'] = `import React, { useState } from 'react';

export default function App() {
  const [count, setCount] = useState(0);

  return (
    <div style={{ fontFamily: 'system-ui, sans-serif', padding: '40px', textAlign: 'center' }}>
      <h1>${name}</h1>
      <p>Modern React 19 Project scaffolded by CodeLens AI</p>
      <button 
        onClick={() => setCount(c => c + 1)}
        style={{ padding: '10px 20px', fontSize: '16px', borderRadius: '8px', cursor: 'pointer', marginTop: '20px' }}
      >
        Count is: {count}
      </button>
    </div>
  );
}`;

      files['src/main.jsx'] = `import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App.jsx';

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`;

      files['index.html'] = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>`;

      files['vite.config.js'] = `import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()]
});`;
    } else if (stack === 'node') {
      files['package.json'] = `{
  "name": "${name.toLowerCase().replace(/[^a-z0-9-]/g, '-')}",
  "version": "1.0.0",
  "main": "server.js",
  "type": "module",
  "scripts": {
    "start": "node server.js",
    "dev": "nodemon server.js"
  },
  "dependencies": {
    "express": "^4.19.2",
    "cors": "^2.8.5",
    "dotenv": "^16.4.5"
  }
}`;

      files['server.js'] = `import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 5000;

app.use(cors());
app.use(express.json());

app.get('/api/health', (req, res) => {
  res.json({ status: 'OK', service: '${name}', timestamp: new Date().toISOString() });
});

app.listen(PORT, () => {
  console.log(\`Server is running on port \${PORT}\`);
});
`;
    } else if (stack === 'cpp') {
      files['CMakeLists.txt'] = `cmake_minimum_required(VERSION 3.20)
project(${name.replace(/[^a-zA-Z0-9_]/g, '_')} VERSION 1.0.0 LANGUAGES CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include_directories(include)

add_executable(\${PROJECT_NAME} src/main.cpp src/math_utils.cpp)
`;

      files['include/math_utils.h'] = `#pragma once

namespace MathUtils {
    long long safeAdd(long long a, long long b);
    long long safeMultiply(long long a, long long b);
}
`;

      files['src/math_utils.cpp'] = `#include "math_utils.h"

namespace MathUtils {
    long long safeAdd(long long a, long long b) {
        return a + b;
    }

    long long safeMultiply(long long a, long long b) {
        return a * b;
    }
}
`;

      files['src/main.cpp'] = `#include <iostream>
#include "math_utils.h"

int main() {
    std::cout << "=== ${name} Initialized ===" << std::endl;
    long long result = MathUtils::safeAdd(100, 250);
    std::cout << "Computation result: " << result << std::endl;
    return 0;
}
`;
    }

    // Common extras: Dockerfile
    if (includeDocker) {
      if (stack === 'spring-boot') {
        files['Dockerfile'] = `FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /workspace
COPY pom.xml .
COPY src src
RUN ./mvnw clean package -DskipTests || mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
VOLUME /tmp
COPY --from=build /workspace/target/*.jar app.jar
ENTRYPOINT ["java","-jar","/app.jar"]
`;
      } else if (stack === 'fastapi') {
        files['Dockerfile'] = `FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`;
      } else if (stack === 'node') {
        files['Dockerfile'] = `FROM node:20-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5000
CMD ["npm", "start"]
`;
      }
    }

    // Common extras: CI/CD
    if (includeCi) {
      files['.github/workflows/ci.yml'] = `name: Build & Verify

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Environment
        run: echo "Environment verified by CodeLens CI"
`;
    }

    files['README.md'] = `# ${name}

> Generated by **CodeLens AI Project Scaffold Engine**

### Tech Stack
* **Framework**: ${stack}
* **Database**: ${database}

### Getting Started
Refer to the manifest files to install dependencies and run locally.
`;

    return files;
  },

  // Package files into a downloadable ZIP Blob
  async createZipBlob(files) {
    const zip = new JSZip();
    for (const [path, content] of Object.entries(files)) {
      zip.file(path, content);
    }
    return await zip.generateAsync({ type: 'blob' });
  },

  // AI Single Page Generator
  async generateAISinglePage(prompt, framework = 'react', style = 'modern-dark') {
    const res = await fetch('/api/generate/single-page', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt, framework, style })
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err.detail || 'Failed to generate single page.');
    }
    const data = await res.json();
    return data.data;
  },

  // AI Full Project Generator with Idea Expansion
  async generateAIFullProject(prompt, name, stack, database) {
    const res = await fetch('/api/generate/full-project', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ prompt, name, stack, database })
    });
    if (!res.ok) {
      const err = await res.json().catch(() => ({}));
      throw new Error(err.detail || 'Failed to generate custom project.');
    }
    const data = await res.json();
    return data.files;
  }
};
